INSERT INTO `Admin` (`admin_id`,`admin_login`, `admin_password`,`admin_status`) VALUES
('1','demo','c514c91e4ed341f263e458d44b3bb0a7','organizer');

INSERT INTO `Organizer` ( `organizer_nickname`, `organizer_name`, `organizer_address`, `organizer_plz`, `organizer_ort`, `organizer_email`, `organizer_fax`, `organizer_phone`, `organizer_password`, `organizer_place`, `organizer_currency`, `organizer_logo`) VALUES
('demo', 'Demo Theater', 'demo', '1234', 'demo', 'info@fusionticket.test', '', '', '', '', 'USD', 'organizer_logo_3.png');

INSERT INTO `ShopConfig` (`shopconfig_lastrun`, `shopconfig_lastrun_int`, `shopconfig_restime`, `shopconfig_restime_remind`, `shopconfig_check_pos`, `shopconfig_delunpaid`, `shopconfig_posttocollect`, `shopconfig_user_activate`, `shopconfig_maxres`, `status`, `res_delay`, `cart_delay`, `shopconfig_run_as_demo`) VALUES
( 0,  10, 7200, 1440, 'No', 'Yes', '2880', 1, 10, 'ON', 660, 600, 0);

INSERT INTO `Color` (`color_id`, `color_code`) VALUES
(1, '#FFFFFF'),
(2, '#FF0000'),
(3, '#00FF00'),
(4, '#0000FF'),
(5, '#FFFF00'),
(6, '#00FFFF'),
(7, '#FF00FF'),
(8, '#CCCCCC'),
(9, '#00CCFF'),
(10, '#000000');

INSERT INTO `Handling` (`handling_id`, `handling_payment`, `handling_shipment`, `handling_alt`, `handling_alt_only`, `handling_fee_fix`, `handling_fee_percent`, `handling_email_template`, `handling_pdf_template`, `handling_pdf_ticket_template`, `handling_pdf_format`, `handling_html_template`, `handling_sale_mode`, `handling_extra`, `handling_text_shipment`, `handling_text_payment`, `handling_expires_min`) VALUES
(1, NULL, NULL, NULL, 'No', '0.00', '0.00', 'res=email_res', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  7200);

INSERT INTO `Handling` (`handling_id`, `handling_payment`, `handling_shipment`, `handling_fee_fix`, `handling_fee_percent`, `handling_email_template`, `handling_pdf_template`, `handling_pdf_ticket_template`, `handling_pdf_format`, `handling_html_template`, `handling_sale_mode`, `handling_extra`, `handling_text_shipment`, `handling_text_payment`, `handling_expires_min`, `handling_alt`, `handling_alt_only`) VALUES
(2, 'cash', 'sp', '0.00', '0.00', 'ord=,send=,payed=', '', '', 'a:2:{i:0;a:4:{i:0;d:0;i:1;d:0;i:2;d:595.279999999999972715158946812152862548828125;i:3;d:260;}i:1;s:8:"portrait";}', 'Put some explanations here', 'sp', NULL, 'Point of sale', 'Cash',  NULL, 0, 'No'),
(3, 'entrance', 'entrance', '0.00', '0.00', 'ord=,send=,payed=', '', '', 'a:2:{i:0;s:0:"";i:1;s:0:"";}', '{de}Besten Dank! Ihre Bestellung wurde bei uns registriert.{/de}\r\n{fr}Merci beaucoup! Votre commande a &eacute;t&eacute; enregistr&eacute;e.{/fr}\r\n{it}Grazie mille! Il Suo ordine stato registrato.{/it}\r\n{en}Thank you very much! Your order was registered.{/en}	\r\n\r\nPut some explanations here in Admin - Handlings', 'sp,www', NULL, '{fr}A l''entr&eacute;e{/fr}{de}Zum Eintritt{/de}{it}A l''entrata{/it}{en}At the entrance{/en}\r\n', '{fr}A l''entr&eacute;e{/fr}{de}Zum Eintritt{/de}{it}A l''entrata{/it}{en}At the entrance{/en}\r\n', NULL, 0, 'No'),
(4, 'invoice', 'email', '1.00', '0.00', 'ord=,send=,payed=', '', '', 'a:2:{i:0;s:0:"";i:1;s:0:"";}', 'Put some explanations here (edit this in Admin - Order Handlings )', 'www', NULL, '{fr}Par &eacute;mail{/fr}{de}Bei E-Mail{/de}{it}Per Email{/it}{en}By e-mail{/en}', '{fr}Virement{/fr}{de}&Uuml;berweisung{/de}{it}Giraconto{/it}{en}Invoice{/en}',  NULL, 0, 'No');

INSERT INTO `Template` (`template_id`, `template_name`, `template_type`, `template_text`) VALUES
(1, 'forgot_passwd', 'systm', '<template deflang="en">\r\n<TO email="$user_firstname $user_lastname &lt;$user_email&gt;"/>\r\n\r\n<subject lang="en" value="Your new password"/>\r\n<subject lang="fr" value="Votre nouveau mot de passe"/>\r\n<subject lang="it" value="La Sua nuova parola d''accesso"/>\r\n\r\n<text lang="en">\r\nDear $user_firstname $user_lastname!\r\n\r\nThere is your new password: $new_password\r\n\r\nHave a nice day\r\n\r\n</text>\r\n\r\n<html lang="en">\r\n<p>Dear $user_firstname $user_lastname!</p>\r\n\r\n<p>There is your new password: <b>$new_password</b></p>\r\n\r\n<p>Have a nice day!</p>\r\n \r\n\r\n</html>\r\n\r\n<text lang="fr">\r\nCher/ChÃ¨re $user_firstname $user_lastname!\r\n\r\nVotre nouveau mot de passe est: $new_password\r\n\r\nMeilleures salutations\r\n\r\n</text>\r\n\r\n<html lang="fr">\r\n<p>Cher/ChÃ¨re $user_firstname $user_lastname!</p>\r\n\r\n<p>Votre nouveau mot de passe est: <b>$new_password</b></p>\r\n\r\n<p>Meilleures salutations</p>\r\n \r\n</html>\r\n\r\n\r\n<text lang="it">\r\nGentile/Gentilissima $user_firstname $user_lastname!\r\n\r\nLa Sua nuova parola d''accesso Ã¨: $new_password\r\nDistinti saluti\r\n\r\n</text>\r\n\r\n<html lang="it">\r\n<p>Gentile/Gentilissima $user_firstname $user_lastname!</p>\r\n\r\n<p>La Sua nuova parola d''accesso Ã¨: <b>$new_password</b></p>\r\n\r\n<p>Distinti saluti</p>\r\n \r\n\r\n</html>\r\n\r\n</template>\r\n'),
(2, 'Signup_email' , 'systm', '<template deflang="en">\r\n<TO email="$user_firstname $user_lastname &lt;$user_email&gt;"/>\r\n\r\n<subject lang="en" value="Confimation of registration"/>\r\n<subject lang="fr" value="Votre nouveau mot de passe"/>\r\n<subject lang="it" value="La Sua nuova parola d''accesso"/>\r\n\r\n<text lang="en">\r\nDear $user_firstname $user_lastname!\r\n\r\nPlease click on the link below:\r\n\r\nPlease copy the following link into your browser:\r\n$link\r\n\r\nThank you\r\n\r\n</text>\r\n\r\n<html lang="en">\r\n<p>Dear $user_firstname $user_lastname!</p>\r\n\r\n<p>Please click on the link below:</p>\r\n\r\n<a href="$link">Click Here</a>\r\n\r\n<p>Thank You</p>\r\n \r\n</html>\r\n\r\n<text lang="fr">\r\nCher/ChÃ¨re $user_firstname $user_lastname!\r\n\r\nVotre nouveau mot de passe est: $new_password\r\n\r\nMeilleures salutations\r\n\r\n</text>\r\n\r\n<html lang="fr">\r\n<p>Cher/ChÃ¨re $user_firstname $user_lastname!</p>\r\n\r\n<p>Votre nouveau mot de passe est: <b>$new_password</b></p>\r\n\r\n<p>Meilleures salutations</p>\r\n \r\n</html>\r\n\r\n\r\n<text lang="it">\r\nGentile/Gentilissima $user_firstname $user_lastname!\r\n\r\nLa Sua nuova parola d''accesso Ã¨: $new_password\r\nDistinti saluti\r\n\r\n</text>\r\n\r\n<html lang="it">\r\n<p>Gentile/Gentilissima $user_firstname $user_lastname!</p>\r\n\r\n<p>La Sua nuova parola d''accesso Ã¨: <b>$new_password</b></p>\r\n\r\n<p>Distinti saluti</p>\r\n \r\n\r\n</html>\r\n\r\n</template>\r\n'),
(3, 'email_res'    , 'systm', '<?xml version="1.0" encoding="UTF-8" ?>\r\n<template deflang="en">\r\n<FROM email="Demo Theater &lt;demo@fusionticket.co.uk&gt;"/>\r\n<TO email="$user_firstname $user_lastname &lt;$user_email&gt;"/>\r\n<CC email="log@demo.mail.com"/>\r\n<BCC email="log@demo.mail.com"/>\r\n<HEADER name="2" value="1"/>\r\n<subject lang="en" value="Confirmation of your tickets, order no. $order_id"/>\r\n<subject lang="de" value="BestÃƒÂ¤tigung Ihre Bestellung no. $order_id"/>\r\n<subject lang="fr" value="Confirmation de Votre commande nr. $order_id"/>\r\n<subject lang="it" value="Conferma del Suo ordine nr. $order_id"/>\r\n\r\n<text lang="en">\r\nTEST SYSTEM - PLEASE EDIT IN TEMPLATES!\r\n\r\nDear $user_firstname $user_lastname!\r\n\r\nThis E-Mail confirms your ticket order from Demo \r\nYour reservation number is: $order_id\r\n\r\nYour tickets are only reserved for a limited time. To purchase the tickets please go to: $order_link$order_id\r\nThank you very much.\r\n\r\n$order_date\r\n\r\n</text>\r\n\r\n<html lang="en">\r\n<b>TEST SYSTEM - PLEASE EDIT IN TEMPLATES!</b>\r\n\r\n<p>Dear $user_firstname $user_lastname!</p>\r\n\r\n<p>This E-Mail confirms your ticket order from Demo </p>\r\n<p>Your purchase number is: <b>$order_id</b></p>\r\n\r\n<p>Your tickets are only reserved for a limited time. To purchase the tickets please go <a href="$order_link$order_id"> here</a>\r\n</p>\r\n\r\n<p>\r\nThank you very much.\r\n</p><p>\r\n$order_date\r\n\r\n</p>\r\n</html>\r\n</template>' );
