<?php
$tbls = array();

$tbls['Admin']['fields'] = array(
  'admin_id' => " int(11) NOT NULL ",
  'admin_login' => " varchar(10) NOT NULL default ''",
  'admin_password' => " varchar(32) NOT NULL default ''",
  'admin_status' => " enum('admin', 'organizer', 'control', 'pos') NOT NULL default 'organizer'",
  'control_organizer_id' => " int(11) NOT NULL default '0'",
  'control_event_ids' => " varchar(100) NOT NULL default ''");
$tbls['Admin']['key'] = array(
  "admin_login" => "KEY `admin_login` (`admin_login`)");
$tbls['Admin']['engine'] = MyISAM;

$tbls['Control']['fields'] = array(
  'control_organizer_id' => " int(11) NOT NULL default '0'",
  'control_login' => " varchar(20) NOT NULL default ''",
  'control_password' => " varchar(32) NOT NULL default ''",
  'admin_status' => " enum('admin', 'organizer', 'control', 'pos') NOT NULL default 'organizer'",
  'control_event_ids' => " varchar(100) NOT NULL default ''");
//$tbls['Control']['key'] = array(
// "color_id" => "PRIMARY KEY id (color_id)");
$tbls['Control']['engine'] = MyISAM;

$tbls['SPoint']['fields'] = array(
  'user_id' => " int(11) NOT NULL default '0'" ,
  'login' => " varchar(50) NOT NULL default ''",
  'password' => " varchar(32) NOT NULL default ''",
  'admin_status' => " enum('admin', 'organizer', 'control', 'pos') NOT NULL default 'organizer'");
$tbls['SPoint']['key'] = array(
  "user_id" => "PRIMARY KEY id (user_id)");
$tbls['SPoint']['engine'] = MyISAM;

$tbls['User']['fields'] = array(
  'user_id' => " int(11) NOT NULL auto_increment",
  'user_lastname' => " varchar(50) NOT NULL default ''",
  'user_firstname' => " varchar(50) NOT NULL default ''",
  'user_address' => " varchar(75) NOT NULL default ''",
  'user_address1' => " varchar(75) NOT NULL default ''",
  'user_zip' => " varchar(10) NOT NULL default ''",
  'user_city' => " varchar(50) NOT NULL default ''",
  'user_state' => " varchar(50) default NULL",
  'user_country' => " varchar(5) NOT NULL default ''",
  'user_phone' => " varchar(50) default NULL",
  'user_fax' => " varchar(50) default NULL",
  'user_email' => " varchar(50) NOT NULL default ''",
  'user_status' => " tinyint(4) NOT NULL default '0'",
  'user_prefs' => " varchar(50) default NULL",
  'user_organizer_ids' => " varchar(100) default NULL",
  'user_order_total' => " int(11) NOT NULL default '0'",
  'user_current_tickets' => " INT( 6 ) NOT NULL default '0'",
  'user_total_tickets' => " INT( 11 ) NOT NULL DEFAULT '0'");
$tbls['User']['key'] = array(
  "user_id" => "primary key id (user_id)");
$tbls['User']['engine'] = InnoDB;
//$tbls['User']['auto_increment'] = 48;

$tbls['auth']['fields'] = array(
  'user_id' => " int(11) NOT NULL default '0'",
  'username' => " varchar(50) NOT NULL default ''",
  'password' => " varchar(32) NOT NULL default ''",
  'active' => " varchar(38) NULL default 'not null'");
$tbls['auth']['key'] = array(
  "username" => "PRIMARY KEY id (username)",
  "password" => "KEY (`password`)");
$tbls['auth']['engine'] = MyISAM;

$tbls['Category']['fields'] = array(
  'category_id' => " int(11) NOT NULL auto_increment",
  'category_event_id' => " int(11) NOT NULL default '0'",
  'category_price' => " decimal(10,2) default NULL",
  'category_name' => " varchar(100) default NULL",
  'category_pm_id' => " int(11) default NULL",
  'category_pmp_id' => " int(11) default NULL",
  'category_ident' => " tinyint(4) default NULL",
  'category_status' => " varchar(5) NOT NULL default ''",
  'category_numbering' => " varchar(5) NOT NULL default 'both'",
  'category_size' => " int(11) default NULL",
  'category_max' => " INT( 11 ) NULL DEFAULT NULL",
  'category_min' => " INT( 11 ) NULL DEFAULT NULL",
  'category_template' => " varchar(30) default NULL",
  'category_color' => " int(11) NOT NULL default '0'",
  'category_data' => " tinytext",
  'category_organizer_id' => " int(11) NOT NULL default '0'");
$tbls['Category']['key'] = array(
  "category_id" => "PRIMARY KEY id (category_id)",
  "category_event_id" => "KEY `category_event_id` (`category_event_id`)");
$tbls['Category']['engine'] = MyISAM;
//$tbls['Category']['auto_increment'] = 87;

$tbls['Category_stat']['fields'] = array(
  'cs_organizer_id' => " int(11) NOT NULL default '0'",
  'cs_category_id' => " int(11) NOT NULL default '0'",
  'cs_total' => " int(11) NOT NULL default '0'",
  'cs_free' => " int(11) NOT NULL default '0'");
$tbls['Category_stat']['key'] = array(
  "cs_category_id" => "PRIMARY KEY id (cs_category_id)");
$tbls['Category_stat']['engine'] = InnoDB;

$tbls['CC_Info']['fields'] = array(
  'cc_info_organizer_id' => "  int(11) NOT NULL default '0'",
  'cc_info_order_id' => "  int(11) NOT NULL auto_increment",
  'cc_info_data' => "  mediumtext NOT NULL",
  'cc_info_key' => "  mediumtext NOT NULL");
$tbls['CC_Info']['key'] = array(
  "cc_info_order_id" => "PRIMARY KEY id (cc_info_order_id)");
$tbls['CC_Info']['engine'] = MyISAM;
//$tbls['CC_Info']['auto_increment'] = 1;

$tbls['Color']['fields'] = array(
  'color_id' => " int(11) NOT NULL auto_increment",
  'color_code' => " varchar(7) NOT NULL default ''");
$tbls['Color']['key'] = array(
  "color_id" => "PRIMARY KEY id (color_id)");
$tbls['Color']['engine'] = MyISAM;
//$tbls['Color']['auto_increment'] = 11;

$tbls['Discount']['fields'] = array(
  'discount_id' => " int(11) NOT NULL auto_increment",
  'discount_event_id' => " int(11) NOT NULL default '0'",
  'discount_name' => " varchar(50) NOT NULL default ''",
  'discount_type' => " varchar(7) NOT NULL default ''",
  'discount_value' => " decimal(10,2) NOT NULL default '0.00'");
$tbls['Discount']['key'] = array(
  "discount_id" => "PRIMARY KEY id (discount_id)");
$tbls['Discount']['engine'] = MyISAM;
//$tbls['Discount']['auto_increment'] = 4;

$tbls['Event']['fields'] = array(
  'event_organizer_id' => " int(11) NOT NULL default '0'",
  'event_id' => " int(11) NOT NULL auto_increment",
  'event_name' => " varchar(100) NOT NULL default ''",
  'event_text' => " text",
  'event_short_text' => " text",
  'event_url' => " varchar(100) default NULL",
  'event_image' => " varchar(100) default NULL",
  'event_ort_id' => " int(11) NOT NULL default '0'",
  'event_pm_id' => " int(11) default NULL",
  'event_categories_nr' => " int(11) default NULL",
  'event_date' => " date default NULL",
  'event_time' => " time default NULL",
  'event_open' => " time default NULL",
  'event_status' => " varchar(5) NOT NULL default ''",
  'event_order_limit' => " int(4) NOT NULL default '0'",
  'event_payment' => " set('CC','POST') NOT NULL default ''",
  'event_template' => " varchar(30) default NULL",
  'event_group_id' => " int(11) NOT NULL default '0'",
  'event_mp3' => " varchar(200) default NULL",
  'event_rep' => " set('main','sub') NOT NULL default 'main,sub'",
  'event_main_id' => " int(11) default NULL",
  'event_type' => " enum('','classics','jazz','blues','funk','pop','rock','folklore','theater','sacred','ballet','opera','humour','music','other','cinema','party','exposition') default NULL");
$tbls['Event']['key'] = array(
  "event_id" => "PRIMARY KEY id (event_id)",
  "event_date" => "KEY `event_date` (`event_date`)");
$tbls['Event']['engine'] = MyISAM;
//$tbls['Event']['auto_increment'] = 4;

$tbls['Event_group']['fields'] = array(
  'event_group_id' => " int(11) NOT NULL auto_increment",
  'event_group_name' => " varchar(100) NOT NULL default ''",
  'event_group_description' => " text",
  'event_group_image' => " varchar(100) NOT NULL default ''",
  'event_group_organizer_id' => " int(11) NOT NULL default '0'",
  'event_group_status' => " varchar(5) NOT NULL default 'unpub'",
  'event_group_start_date' => " date default NULL",
  'event_group_end_date' => " date default NULL",
  'event_group_type' => " enum('','festival','tournee','theatre') default NULL");
$tbls['Event_group']['key'] = array(
  "event_group_id" => "PRIMARY KEY id (event_group_id)");
$tbls['Event_group']['engine'] = MyISAM;
$tbls['Event_group']['auto_increment'] = 3;
$tbls['Event_stat']['fields'] = array(
  'es_organizer_id' => " int(11) NOT NULL default '0'",
  'es_event_id' => " int(11) NOT NULL default '0'",
  'es_total' => " int(11) NOT NULL default '0'",
  'es_free' => " int(11) NOT NULL default '0'");
$tbls['Event_stat']['key'] = array(
  "es_event_id" => "PRIMARY KEY id (es_event_id)");
//$tbls['Event_stat']['engine'] = InnoDB;
// $tbls['Event_stat']['auto_increment'] = 3;
$tbls['Handling']['fields'] = array(
  'handling_id' => " int(11) NOT NULL auto_increment",
  'handling_organizer_id' => " int(11) NOT NULL default '0'",
  'handling_payment' => " enum('invoice','entrance','cash','authorize_aim','cc','paypal') default NULL",
  'handling_shipment' => " enum('email','post','entrance','sp') default NULL",
  'handling_fee_fix' => " decimal(3,2) default NULL",
  'handling_fee_percent' => " decimal(3,2) default NULL",
  'handling_email_template' => " tinytext",
  'handling_pdf_template' => " tinytext",
  'handling_pdf_ticket_template' => " tinytext",
  'handling_pdf_format' => " tinytext",
  'handling_html_template' => " mediumtext",
  'handling_sale_mode' => " set('sp','www') default NULL",
  'handling_extra' => " text",
  'handling_text_shipment' => " mediumtext",
  'handling_text_payment' => " mediumtext",
  'handling_delunpaid' => " enum('Yes','No') NOT NULL default 'No'",
  'handling_expires_min' => " int(11) default NULL",
  'handling_alt' => " int(11) default NULL",
  'handling_alt_only' => " enum('Yes','No') NOT NULL default 'No'");
$tbls['Handling']['key'] = array(
  "handling_id" => "PRIMARY KEY id (handling_id)");
$tbls['Handling']['engine'] = InnoDB;
//$tbls['Handling']['auto_increment'] = 33;

$tbls['Order']['fields'] = array(
  'order_id' => " int(11) NOT NULL auto_increment",
  'order_organizer_id' => " int(11) NOT NULL default '0'",
  'order_user_id' => " int(11) NOT NULL default '0'",
  'order_session_id' => " varchar(32) NOT NULL default ''",
  'order_tickets_nr' => " int(11) NOT NULL default '0'",
  'order_total_price' => " decimal(10,2) NOT NULL default '0.00'",
  'order_date' => " datetime NOT NULL default '0000-00-00 00:00:00'",
  'order_shipment_status' => " enum('none','send') NOT NULL default 'none'",
  'order_payment_status' => " enum('none','payed') NOT NULL default 'none'",
  'order_payment_id' => " varchar(32) default NULL",
  'order_handling_id' => " int(11) NOT NULL default '0'",
  'order_status' => " enum('ord','cancel','reemit','trash','res','pros') NOT NULL default 'ord'",
  'order_reemited_id' => " int(11) default NULL",
  'order_fee' => " decimal(10,2) default NULL",
  'order_place' => " varchar(11) NOT NULL default 'www'",
  'order_date_expire' => "datetime NOT NULL default '0000-00-00 00:00:00'");
$tbls['Order']['key'] = array(
  "order_id" => "PRIMARY KEY id (order_id)",
  "order_status" => "KEY `order_status` (`order_organizer_id`,`order_handling_id`,`order_shipment_status`,`order_payment_status`,`order_status`)");
$tbls['Order']['engine'] = InnoDB;
//$tbls['Order']['auto_increment'] = 1;

$tbls['Organizer']['fields'] = array(
  'organizer_id' => " int(11) NOT NULL auto_increment",
  'organizer_nickname' => " varchar(10) NOT NULL default ''",
  'organizer_name' => " varchar(100) NOT NULL default ''" ,
  'organizer_address' => " varchar(100) NOT NULL default ''" ,
  'organizer_plz' => " varchar(100) NOT NULL default ''",
  'organizer_ort' => " varchar(100) NOT NULL default ''" ,
  'organizer_state' => " varchar(50) default NULL",
  'organizer_country' => " varchar(50) default NULL",
  'organizer_email' => " varchar(100) NOT NULL default ''" ,
  'organizer_fax' => " varchar(100) NOT NULL default ''" ,
  'organizer_phone' => " varchar(100) NOT NULL default ''" ,
  'organizer_password' => " varchar(32) NOT NULL default ''" ,
  'organizer_place' => " varchar(100) NOT NULL default ''" ,
  'organizer_currency' => " char(3) NOT NULL default 'GBP'" ,
  'organizer_logo' => " varchar(100) default NULL");
$tbls['Organizer']['key'] = array(
  "organizer_id" => "PRIMARY KEY id (organizer_id)");
$tbls['Organizer']['engine'] = InnoDB;
//$tbls['Organizer']['auto_increment'] = 1;

$tbls['Ort']['fields'] = array(
  'ort_organizer_id' => " int(11) NOT NULL default '0'",
  'ort_id' => " int(11) NOT NULL auto_increment",
  'ort_name' => " varchar(100) NOT NULL default ''",
  'ort_phone' => " varchar(50) default NULL",
  'ort_plan_nr' => " varchar(100) NOT NULL default ''",
  'ort_url' => " varchar(100) NOT NULL default ''",
  'ort_image' => " varchar(100) default NULL",
  'ort_address' => " varchar(75) NOT NULL default ''",
  'ort_address1' => " varchar(75) NOT NULL default ''",
  'ort_zip' => " varchar(20) NOT NULL default ''",
  'ort_city' => " varchar(50) NOT NULL default ''",
  'ort_state' => " varchar(50) default ''",
  'ort_country' => " varchar(50) NOT NULL default ''",
  'ort_pm' => " text default ''",
  'ort_fax' => " varchar(50) default NULL");
$tbls['Ort']['key'] = array(
  "ort_id" => "primary key id (ort_id)");
$tbls['Ort']['engine'] = MyISAM;
//$tbls['Ort']['auto_increment'] = 1;

$tbls['PlaceMap2']['fields'] = array(
  'pm_organizer_id' => " int(11) default NULL",
  'pm_id' => " int(11) NOT NULL auto_increment",
  'pm_ort_id' => " int(11) NOT NULL default '0'",
  'pm_event_id' => " int(11) default NULL",
  'pm_name' => " varchar(30) NOT NULL default ''",
  'pm_image' => " varchar(100) default NULL");
$tbls['PlaceMap2']['key'] = array(
  "pm_id" => "primary key id (pm_id)");
$tbls['PlaceMap2']['engine'] = MyISAM;
//$tbls['PlaceMap2']['auto_increment'] = 36;

$tbls['PlaceMapPart']['fields'] = array(
  'pmp_id' => " int(11) NOT NULL auto_increment",
  'pmp_pm_id' => " int(11) NOT NULL default '0'",
  'pmp_ident' => " tinyint(4) NOT NULL default '0'",
  'pmp_ort_id' => " int(11) NOT NULL default '0'",
  'pmp_event_id' => " int(11) default NULL",
  'pmp_name' => " varchar(30) NOT NULL default ''",
  'pmp_width' => " int(11) NOT NULL default '0'",
  'pmp_height' => " int(11) NOT NULL default '0'",
  'pmp_scene' => " enum('north','east','south','west','center') NOT NULL default 'north'",
  'pmp_shift' => " enum('0','1') NOT NULL default '0'",
  'pmp_data' => " text NOT NULL",
  'pmp_data_orig' => " text",
  'pmp_expires' => " int(11) default NULL",
  'pmp_organizer_id' => " int(11) default NULL");
$tbls['PlaceMapPart']['key'] = array(
  "pmp_id" => "primary key id (pmp_id)");
$tbls['PlaceMapPart']['engine'] = MyISAM;
//$tbls['PlaceMapPart']['auto_increment'] = 34;

$tbls['PlaceMapZone']['fields'] = array(
  'pmz_id' => " int(11) NOT NULL auto_increment",
  'pmz_pm_id' => " int(11) NOT NULL default '0'",
  'pmz_ident' => " tinyint(4) NOT NULL default '0'",
  'pmz_name' => " varchar(50) NOT NULL default ''",
  'pmz_short_name' => " varchar(10) default NULL",
  'pmz_color' => " varchar(10) default NULL",
  'pmz_organizer_id' => " int(11) NOT NULL default '0'");
$tbls['PlaceMapZone']['key'] = array(
  "pmz_id" => "primary key id (pmz_id)",
  "pm_id" => "KEY `pm_id` (`pmz_pm_id`)" ,
  "pmz_ident" => "KEY `pmz_ident` (`pmz_ident`)");
$tbls['PlaceMapZone']['engine'] = MyISAM;
$tbls['PlaceMapZone']['auto_increment'] = 51;

$tbls['Seat']['fields'] = array(
  'seat_id' => " int(11) NOT NULL auto_increment",
  'seat_event_id' => " int(11) NOT NULL default '0'",
  'seat_category_id' => " int(11) NOT NULL default '0'",
  'seat_user_id' => " int(11) default NULL",
  'seat_order_id' => " int(11) default NULL",
  'seat_row_nr' => " varchar(5) default NULL",
  'seat_zone_id' => " int(11) default NULL",
  'seat_pmp_id' => " int(11) default NULL",
  'seat_nr' => " int(11) NOT NULL default '0'",
  'seat_ts' => " int(11) default NULL",
  'seat_sid' => " varchar(32) default NULL",
  'seat_price' => " decimal(10,2) default NULL",
  'seat_discount_id' => " int(11) default NULL",
  'seat_code' => " varchar(16) default NULL",
  'seat_status' => " varchar(5) NOT NULL default 'free'",
  'seat_organizer_id' => " int(11) NOT NULL default '0'",
  'seat_sales_id' => " int(11) default NULL");
$tbls['Seat']['key'] = array(
  "seat_id" => "primary key id (seat_id)",
  "seat_event_id" => "KEY `seat_event_id` (`seat_event_id`,`seat_category_id`,`seat_order_id`,`seat_ts`,`seat_status`)");
$tbls['Seat']['engine'] = MyISAM;
//$tbls['Seat']['auto_increment'] = 3004;

$tbls['ShopConfig']['fields'] = array(
  'shopconfig_id' => " int(11) NOT NULL auto_increment",
  'shopconfig_organizer_id' => " int(11) NOT NULL",
  'shopconfig_lastrun' => " datetime NOT NULL default '0000-00-00 00:00:00'",
  'shopconfig_lastrun_int' => " int(11) NOT NULL default '10'",
  'shopconfig_restime' => " int(11) NOT NULL default '0'",
  'shopconfig_restime_remind' => " int(11) NOT NULL default '0'",
  'shopconfig_check_pos' => " enum('No','Yes') NOT NULL default 'No'",
  'shopconfig_delunpaid' => " enum('Yes','No') NOT NULL default 'Yes'",
  'shopconfig_posttocollect' => " varchar(20) NOT NULL default '2'",
  'shopconfig_user_activate' => " ENUM( 'Yes', 'No' ) NOT NULL DEFAULT 'Yes'",
  'shopconfig_maxres' => " INT( 11 ) NOT NULL DEFAULT '10'",
  'status' => " char(3) NOT NULL default 'ON'");
$tbls['ShopConfig']['key'] = array(
  "shopconfig_id" => "primary key id (shopconfig_id)");
$tbls['ShopConfig']['engine'] = MyISAM;
//$tbls['ShopConfig']['auto_increment'] = 1;

$tbls['Template']['fields'] = array(
  'template_id' => " int(11) NOT NULL auto_increment",
  'template_name' => " varchar(30) NOT null default ''",
  'template_type' => " varchar(5) NOT NULL default ''",
  'template_text' => " text NOT null",
  'template_ts' => " timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP",
  'template_status' => " varchar(5) NOT null default 'new'",
  'template_code' => " text",
  'template_organizer_id' => " int(11) NOT null default '0'");
$tbls['Template']['key'] = array(
  "template_id" => "primary key id (template_id)",
  "template_name" => "KEY `template_name` (`template_name`)");
$tbls['Template']['engine'] = MyISAM;
//$tbls['Template']['auto_increment'] = 21;


?>