<?php
define("cart_cont_mess","Please check your order. You have 15 minutes before your reserved
        tickets are released back to sale, so please either order more tickets or continue
        with your order. <br><br>To change your tickets remove the ones you have reserved
        and click &apos;Order More Tickets&apos;.");

deFine("actions","Actions");
define("act_err","User not found or allready activated.");
define("act_is_sent","Your activation email has been sent to your e-mail");
define("act_mess_line","Please check you email to activate your account.<br><br>");
define("act_name","Activate account");
define("act_notarr","Activation email still not arrived?");
define("act_note","Enter your e-mail address. Click on &apos;Send&apos; and a new activation
        email will be sent to your e-mail address.");
define("act_norecived","If you haven&apos;t recived an activation email within a few hours, please follow  the following <strong>link</strong>");

define("act_send","Send");
define("add","Add");
define("address1","Address");
define("address","Address");
define("administration","Administration");
define("admin_list","List");
define("admin_select_organizer","Select an organizer");
define("agb_name","Put your sales conditions in &apos;agb.html&apos;");
define("agenda_only","Agenda only");
define("agrement","I have read and agree to the General Terms of Sale.");
define("alreadyexist","This e-mail is already registered in our database!");
define("already_exist","This word exist already. Take another.");
define("already_no_sale","Not on sale yet");  //changed lou5
define("already_pub","Already published");
define("also_sub","Subevents also");
define("authorize_aim","Authorize.net AIM");
define("authorize_sim","Authorize.net SIM");
define("autocancel","After this time your order is automaticaly canceled!");
define("autonumber_pmz","Automatic numbering");
//B
define("back_shop","Order more tickets");
define("ballet","Ballet");
define("bcm_mbr","Become a member");
define("becomemember","Become a member");
define("blues","Blues");
define("bs","Ord.");
define("buytimeleft","You have ~DAYS~ Days, ~HOURS~ Hours, ~MINS~ Mins, ~SECS~ Seconds left to confirm your order!");
define("by_post","Send by post");
//C
define("calendar","Calendar");
define("cancel","Cancel order?");
define("canceled","Canceled");
define("cancel_and_delete","Status changed to &apos;Canceled&apos; and tickets deleted");
define("cancel_order","Status changed to &apos;Canceled&apos; and tickets deleted");
define("cancel_order_now","Status changed to &apos;Canceled&apos;");
define("cancel_ticket","Cancel ticket");
define("cannot_find_seat","Cannot find seat");
define("cannot_seal","Internal error: Cannot seal credit card info");
define("cannot_store","Internal error: Cannot store credit card info");
define("cart_empty","Your cart is empty.");
define("cart_empty_pos","No orders to be finished");
define("cart_not_updated","Cart is not updated");
define("cart_try_again","Try again, please");
define("cart_updated","Cart is updated");
define("cash","Cash");
define("categories","Categories");
define("categories_and_prices","Categories and prices");
define("categories_prices","Categories and prices");
define("category","Cat.");
define("category_add_title","Add a new Category ");
define("category_color","Color for category");
define("category_data","Category data");
define("category_event_id","Event nr.");
define("category_id","Category Nr.");
define("category_name","Category Name");
define("category_numbering","Category numbering");
define("category_numbering_both","Rows and seats numbered");
define("category_numbering_none","Seats without number (open seating)");
define("category_numbering_rows","Only rows numbered");
define("category_numbering_seat","Only seat number (no rows)");
define("category_pmp_id","Category seat chart part ID");
define("category_pm_id","Category Chart ID.");
define("category_price","Category Price");
define("category_size","Category size");
define("number_taken","Seats sold");	//added lou5
define("category_sold","Category sold");
define("category_sold_out","SOLD");
define("category_template","Template for tickets");
define("category_title","All Categories");
define("category_update_title","Edit category");
define("category_view_title","Category");
define("cat_description","Seating Sections and prices");
define("cat_sold_out","Category sold");
define("cat_stat_error","Error - category stats not updated");
define("cat_stat_success","Succes - category stats updated");
define("cat_ticketprice","Ticket Price");
define("cat_ticketsection","Ticket Section");
define("cat_total","Total");
define("cc","Credit Card");
define("cc_code","Checknumber");
define("cc_error","Credit card error");
define("cc_exp","Expire Date");
define("cc_name","Credit card owner name");
define("cc_number","Card number");
define("cc_owner","Name on the card");
define("change_event","Change event");
define("change_order_status_failed","Can not change status");
define("change_order_to_no_payed","Change status to &apos;Not paid&apos;");
define("change_order_to_ord","Change status to &apos;Ordered&apos;");
define("change_order_to_payed","Change status to &apos;Paid&apos;");
define("change_status_to_no_payed","Change status to &apos;no paid&apos;?");
define("change_status_to_no_send","Change status to &apos;not sent&apos;?");
define("change_status_to_ord","Change status to &apos;ordered&apos;?");
define("change_status_to_payed","Change status to &apos;Paid&apos;?");
define("change_status_to_send","Change status to &apos;Sent&apos;?");
define("change_status_to_send_email","Change status to &apos;Sent&apos; and send by e-mail?");
define("charges","Charges");
define("check","Check");
define("checked","Checked");
define("checkout","Check Out");
define("check_success","Ticket check OK");
define("choice","Choose");
define("choice_cat","Select a category");
define("choice_cat_title","Select category");
define("choice_place_title","Select a seat");
define("choice_please","Choose please");
define("choice_qty","Number of seats");
define("cinema","Cinema");
define("city","City");
define("classics","Classical music");
define("clear","Clear");
define("click_here","Click here, please");
define("click_on_reserve","2.Click on &apos;Reserve&apos;");
define("codebar","Barcode");
define("com","Ordered");
define("comp","Compiled");
define("compilation_succeed","Success - Template compiled");
define("compile_all","Compile all");
define("conditions"," I have read and agree to the General Terms of Sale.");
define("confirmemail","Confirm E-mail Address");
define("confirmpassword","Confirm password");
define("confirm_and_print","Confirm and Print");
define("confirm_no","No");
define("confirm_yes","Yes");
define("continue","Continue");
define("control_add_title","Add ticket taker");
define("control_admin","Ticket takers");
define("control_events_list","Events");
define("control_event_ids","Events");
define("control_login","Login");
define("control_title","All ticket takers");
define("control_update_title","Edit ticket taker");
define("control_view","Ticket taker");
define("copy","Copy");
define("copy_main_pm","Copy main seat chart");
define("correct_errors_first","Correct errors first");
define("country","Country");
define("create","Create");
//D
define("date","Date");
define("dates_localities","Dates and localities");
define("date_format","%A %e %B %Y");
define("date_venue","Date,Venue");
define("define","Define");
define("delete_confirm_msg","Delete this event?");
define("delete_item","Delete?");
define("delete_subs_first","Delete sub events first");
define("delete_ticket","Delete the ticket? Ticket Nr:");
define("discount","Discount");
define("discounts","Discounts");
define("discount_add_title","Add a discount");
define("discount_update_title","Update Discount");
define("discount_id","Discount nr");
define("discount_name","Discount Name");
define("discount_title","All discounts");
define("discount_type","Discount type");
define("discount_type_fixe","Fixed discount");
define("discount_type_percent","Percent discount");
define("discount_value","Discount value");
define("div_dates","Diverses dates");
define("doors_open","Doors open");
//E
define("edit","Edit");
define("edit_pm","Modify seat chart");
define("email","E-mail Address");
define("email_failed","Internal error: impossible to send the e-mail. Order Number is:");
define("email_valid","Please enter a valid email address");
define("email_match","The Emails do not match.");
define("empty_trash","Empty");
define("end_date","End date");
define("enter_guest","Personal information");
define("entrance","At the entrance");
define("error","Error");
define("error_loading_user","Error occurdt when loading user data ");
define("et_church","Church music");
define("et_cinema","Cinema");
define("et_classics","Classical music");
define("et_expo","Expo");
define("et_folk","Folk");
define("et_humour","Humour");
define("et_jbf","Jazz/Blues/Funk");
define("et_music","Music");
define("et_opbal","Opera/Ballet");
define("et_other","Other");
define("et_party","Party");
define("et_pr","Pop/Rock");
define("et_theater","Theater");
define("event","Event");
define("event_add_title","Add a new event");
define("event_admin","Events");
define("event_cats","Categories:");
define("event_date","Date");
define("event_discounts","Discounts");
define("event_groups","Event Groups");
define("event_group_add_title","Add an event group");
define("event_group_admin","Event Groups");
define("event_group_type","Group Type");//added lou5
define("event_group_description","Description");
define("event_group_end_date","End date");
define("event_group_id","Group ID");
define("event_group_image","Picture");
define("event_group_name","Name");
define("event_group_start_date","Start date");
define("event_group_title","All event groups");
define("event_group_update_title","Modify the event group");
define("event_id","Event nr");
define("event_image","Event picture");
define("event_image_url","Picture URL");
define("event_list","Event list");
define("event_mp3","MP3");
define("event_name","Event Name");
define("event_open","Doors open");
define("event_order_limit","Order limit");
define("event_order_limit_exceeded","Sorry, The number of seats that you can order for this event is limited!");
define("event_organizer","Organizer");
define("event_ort_id","Venue");
define("event_ort_name","Venue Name");	//changed lou5
define("event_payment","Payment mode");
define("event_pm_ort_id","Seat chart");
define("event_rep","Repeatability");
define("event_rep_main","Multiple");
define("event_rep_unique","Unique");
define("event_short_text","Event short text");
define("event_sold","Event sold out");
define("event_sold_out","Event sold");
define("event_start","Event start");
define("event_stats_title","Statistics");
define("event_stat_error","Error - event stats not updated");
define("event_stat_success","Success - event stats updated");
define("event_template","Template for tickets");
define("event_text","Event long text");
define("event_time","Event Begins");
define("event_title","All Events");
define("event_type","Type");
define("event_update_title","Edit event");
define("event_url","Homepage");
define("ev_datum","Date, Venue");
define("ev_name","Event");
define("ev_ticket","Tickets");
define("excel_admin","Excel");
define("expired","EXPIRED");
define("expired_tickets","Expired tickets:");
define("expires_in","Expires in");
define("export_entrant_NotSended","'Not Sent' orders only");
define("export_admin","Export");
define("export_admin_title","Export Data");
define("export_cc","Credit Cards");
define("export_cc_count","Credit Card count");
define("export_cc_submit","Export");
define("export_cc_title","Export Credit Card numbers");
define("export_xl","Sales data");
define("export_xl_title","Sales data");
define("export_templates","Templates");		//added lou5
define("export_template_id","Choose Template ");	//added lou5
define("export_template_file","Filename");		//added lou5
define("export_submit","Export It!");		//added lou5
define("export_entrant_title","Export Attendees");		//added lou5
define("export_entrant","Orders");		//added lou5
define("export_entrant_event","Choose Event");		//added lou5
//define("export_entrant_NotSended","Not sent");		//added lou5
define("export_xml_event","Event in XML");
define("export_xml_event_event","Choose an event");
define("export_xml_event_file","Filename");
define("export_xml_event_submit","Export it!");
define("export_xml_event_title","Export Data");	//changed lou5 (3 pages use same title)
define("exposition","Exposition");
define("exp_rm","Expires in");
//F
define("fax","Fax Number");
define("fax_short","The fax number is too short");
define("fax_long","The fax number is too long");
define("file_admin","Files");
define("file_dir_name","Directory Name");
define("file_mkdir","Directories");
define("file_name","File Name");
define("file_not_found","File not found");
define("file_upload","Upload files");
define("filling_stats","Tabelle f&uuml;r Statistik");
define("firstname","First name");
define("firstpage","First page");
define("first_row","First row");
define("first_seat","First seat");
define("flip","Flip");
define("folklore","Folklore");
define("forgot_pass","Forgotten your password?");
define("forgot_password","Forgotten your password?");
define("forgot_pass_note","Introduce here your e-mail address.<br /> Click on Send password
        and a new password will be send to you by e-mail");
define("forgot_pwd","Forgot my password.");
define("free","Free");
define("free_places","FREE");
define("from","From");
define("FullName","Naam");
define("funk","Funk");
//G
define("garbage","Garbage");
define("generate_xl","Generate sales document");
define("go_back","Click Here to go back");
define("go_pay","Order");
define("graph_stats","Graphic stats");
define("guest","Guest");
//H
define("handlings","Payments");
define("handling_add_title","Add an order handling");
define("Handling_cont_mess","");
define("handling_email_template_ord","Email Template for order");
define("handling_email_template_payed","Email Template for payment");
define("handling_email_template_send","Email Template for shipment");
define("handling_fee_fix","Fee fix");
define("handling_fee_percent","Fee percent");
define("handling_html_template","HTML Template for explanations");
define("handling_id","ID");
define("handling_payment","Payment");
define("handling_pdf_template","PDF Template for invoice/receipt");
define("handling_pdf_ticket_template","PDF Ticket template");
define("handling_sale_mode","Sale mode");
define("handling_shipment","Shipment");
define("handling_text_payment","Payment label");
define("handling_text_shipment","Shipment label");
define("handling_title","Order handlings");
define("handling_expires_min","Minutes until handling expires");	//added lou5
define("helpme","Help information");
define("home","Home");
define("homepage","Homepage");
define("humour","Humour");
//I
define("id","ID");
define("img_loading_problem","Image loading Problem");
define("import","Import");
define("import_csv_file","Filename");		//added lou5
define("langauge","Language Name");		//added lou5
define("import_admin","Import");
define("import_admin_title","Import Data");
define("import_xml","Event in XML");  //changed lou5
define("import_template","Templates");
define("import_langauge","Language files");
define("import_xml_file","XML file");
define("import_xml_submit","Import it!");
define("import_xml_title","Import Data");	//changed lou5  (same field used in 3 different pages)
define("indexpage","Index");
define("info1","1.Select your seat(s) please");
define("info2","2.Click on &apos;Reservate&apos;");
define("internal_error","Internal error");
define("invalid","invalid");
define("invalid_date","Invalid Date");
define("invalid_name","Invalid name");
define("invalid_number","Invalid credit card number");
define("invoice","Transfer");
define("inv_row","Invert rows");
define("inv_seat","Invert seat");
define("in_use","This object is used and cannot be deleted");
//J
define("jazz","Jazz");
//K
define("kasse","Check out");
define("kassecontent","Check out");
define("kasse_empty","Il n&apos;y a pas de commandes en suspens");
define("kasse_lang","Language");
define("kasse_name","Name of point of sale");
define("kasse_nickname","Login");
define("kreditkarte","Credit card");
//L
define("labels","Labels");
define("label_text","Text");
define("label_type","Type");
define("label_type_exit","Exit");
define("label_type_row_east","Row nr. right");
define("label_type_row_west","Left row nr. ");
define("label_type_seat_north","Nr.of seat above");
define("label_type_seat_south","Nr of seat below");
define("label_type_text","Text");
define("lang","Language");
define("lastname","Last name");
define("lastpage","Last page");
define("legende","Explanation");
define("limit","Unfortunatly you have exceeded amount of alowed reserved tickets. To check
        your orders click <a href='index.php?personal_page=orders'>here</a>.");
define("login","Login name");
define("login_invalid","Invalid login");
define("login_name","Login name");
define("logout","Log out");
define("log_error","Login Error");
define("log_err_not_act","You are not activated.");
define("log_err_not_act_info","<br />Please activate your account!<p>Please check your email for the activation email. Also
        check your spam folder. Then follow the link to activate your account</p><p>If you
        still haven&apos;t recieved anything after a hour please click <a href='resend_activation.php'
        here</a> to resend activation email.</p>");
define("log_err_wrong_usr","Wrong username or password! ");
define("log_err_wrong_usr_info","<p>Please try again, remembering that the username and password are case sensitive.<br />If you have forgoten your username
        or password please click <a href='forgot_password.php'>here</a></p>");
define("longdate_format","%Y-%m-%d %H:%M:%S");
//M
define("mandatory","Field Required");
define("map","Chart");
define("mayuse","I agree that {\$organizer->organizer_name} may use my details to send
        me information about future events and other pepper related matters, and that they
        will not pass on my details to any 3rd party.");
define("memberinfo","Please enter your details below. To buy tickets you are required to
        sign up, it is recommend that you sign up before you go to reserve tickets.");
define("member","Member");
define("member_info","Please enter your email address and password ");
define("minutes","min.");
define("Mostly you will recive your email straight away. If you didn&apos;t reciveive our
        email, please check your spam folder too.","");
define("MP3_loading_problem","Loading problem MP3 file");
define("multi","Add subevent");
define("music","Music");
//N
define("new","new");
define("new_event_image","New  picture");
define("new_order_created","New order created");
define("new_order_failed","New order creation failed");
define("new_organizer_logo","New logo");
define("new_ort_image","New picture");
define("new_password","New password");
define("new_pmz","New Zone");
define("new_pm_zone","Add a new zone");
define("next","Next");
define("nextpage",">>>>>>>");
define("next_events","Next events");
define("next_expire","Next expire in:");
define("nickname","Nickname");
define("none","None");
define("normal","Normal");
define("nosale_confirm_msg","Remove from sale?");
define("nosale_failure","Failure");
define("nosale_status_updated","Status updated");
define("nosale_success","Success");
define("note_mbr","Check your email");
define("notpaid","Not Paid");
define("notsent","Not Sent");
define("not_number","Enter a number without -().");
define("not_to_be2"," ");
define("not_to_be","If you are not");
define("not_valid_email","E-mail is invalid");
define("not_valid_event","Event is not valid");
define("no_color","No color");
define("no_result","No result");
define("no_send_order_post","Change status to &apos;Not sent&apos;");
define("no_tick_res","You have no tickets reserved.");
define("number_seats","Number of seats");
define("number_tickets","Number of tickets");
define("nur_schweiz","Only in Switzerland");
//O
define("old_order_canceled","Old order cancelled");
define("old_order_not_canceled","Old order not canclled");
define("old_password","Old password");
define("only_rows_numbered","Only rows numbered");
define("open","Doors open");
define("open_with_acrobat","Open Orders in Acrobat");
define("opera","Opera");
define("options","Options");
define("option_update_title","Config Shop Auto-updates");
define("orclick","Or Click below to:");
define("Orderdate","Date Ordered");
define("ordered","Ordered");
define("ordernumber","Order Number");
define("order","Order");
define("orders","Orders");
define("ordertickets","To Order Tickets Click below:");
define("order_admin","Order overview");
define("order_allready_cancelled","Order Allready cancelled");
define("order_canceled","Order cancelled");
define("order_cannot_change_to_payed","Can not change status to &apos;Payed&apos;");
define("order_cannot_change_to_send","Can not set status to &apos;Sent&apos;");
define("order_cannot_reemit","Can not reemit");
define("order_date","Order date");
define("order_details","Order details");
define("order_fee","Fee");
define("order_id","Order Number");
define("order_it","Order");
define("order_limit","Order limit");
define("order_list_title","All Orders");
define("order_more_tickets","Order more tickets");
define("order_not_canceled","Order not cancelled");
define("order_not_found","Order not found");
define("order_now","Order now");
define("order_nr","Order-Nr ");
define("order_payment_mode","Payment mode");
define("order_payment_status","Payment status");
define("order_price","Total Price");
define("order_reg","Order registered");
define("order_options","Order / Site Options");
define("order_shipment_mode","Shipment mode");
define("order_shipment_status","Shipment status");
define("order_status","Status");
define("order_status_cancel","Cancelled");
define("order_status_changed","Order Status Changed Successfully");
define("order_status_email","Sent by E-Mail");
define("order_status_ord","Ordered");
define("order_status_payed","Payed");
define("order_status_post","Sent by Post");
define("order_status_reemit","Reemited");
define("order_status_send","Sent");
define("order_status_sp","Points of sale");
define("order_tickets_nr","Number of tikets");
define("order_total","Order Total");
define("order_total_price","Total Price");
define("order_type_canceled","Cancelled");
define("order_type_email","E-Mail");
define("order_type_ordered","Ordered");
define("order_type_pending","Pending");
define("order_type_payed","Payed");
define("order_type_post","Post");
define("order_type_reemited","Reemitted");
define("order_type_reserved","Reserved");
define("order_type_sended","Sent");
define("order_type_spoint","Point of sale");
define("ord","Ordered");
define("organizer_address","Address");
define("organizer_add_title","Add organizer");
define("organizer_admin","Organizer");
define("organizer_currency","Currency");
define("organizer_email","E-Mail");
define("organizer_fax","Fax");
define("organizer_id","Organizer Nr.");
define("organizer_logo","Logo");
define("organizer_name","Name");
define("organizer_nickname","Nickname");
define("organizer_not_found","Organizer not found");
define("organizer_ort","Town");
define("organizer_state","State");	//added lou5
define("organizer_country","Country");	//added lou5
define("organizer_phone","Phone");
define("organizer_place","Town");
define("organizer_plz","Zip"); //changed lou5
define("organizer_title","All Organizers");
define("organizer_update_title","Edit organizer");
define("ort","Venue");
define("ort_address1","Address 1");
define("ort_address","Address");
define("ort_add_title","Add venue");
define("ort_admin","Venues");
define("ort_city","City");	//changed lou5
define("ort_state","State");	//added lou5
define("ort_country","Country");
define("ort_country_name","Country");
define("ort_fax","Fax");
define("ort_id","Venue ID");
define("ort_image","Venue picture");
define("ort_name","Venue Name");
define("ort_phone","Phone");
define("ort_plan_nr","Number on plan");
define("ort_pm","Googlemaps link");//lou
define("ort_title","Venues");
define("ort_update_title","Edit venue");
define("ort_url","Homepage");
define("ort_zip","Zip");	//changed lou5
define("other","Other");
define("outdated","outdated");
//P
define("page_format_custom","Custom");
define("page_format_default","Default");
define("page_format_std","Standard");
define("page_orientation_landscape","Landscape");
define("page_orientation_portrait","Portrait");
define("paid","Paid");
define("party","Party");
define("parzial_price","Total without charges");
define("passwd_changed","Your new password was sent to your e-mail.");
define("password2","Repeat password");
define("password","Password");
define("pass_match","The Passwords do not match");
define("pass_too_short","Password too short");
define("payed","Payed");
define("payed_and_send","Payed and Sent");
define("payhere","<br><br>To Pay Now, Check Here:");
define("payment","Payment");
define("payment_add_title","Add a type of payment");
define("payment_admin","Order Handlings");
define("payment_cc","Credit card");
define("payment_email_template","Email Template");
define("payment_fee_fixe","Fix fee ");
define("payment_fee_percent","Percent fee ");
define("payment_mode","Payment type");
define("payment_post","Post");
define("payment_send","Tickets Shipment");
define("payment_title","All types of payment");
define("payment_update_title","Modify the payment type");
define("paypal","PayPal");
define("paypal_pay","Make payments with PayPal - it's fast, free and secure!");
define("pay","Pay");
define("paytimeleft","You Have ~MINS~ Mins and ~SECS~ Seconds to pay for your order!");
define("pay_accept","Payment accepted");
define("pay_cancel","Payment canceled");
define("pay_error","Select the payment mode");
define("pay_methods","Payment");
define("pay_refused","Payment not accepted");
define("pay_reg","Payment registered");
define("pdf_failed","Internal error: Impossible to produce pdf - Order Nr:");
define("pdf_paper","PDF Page format");
define("personal","Personal Details");
define("pers_cancel","Canceled");
define("pers_info","Personal information");
define("pers_mess2","To change or see your orders in more detail please click
         <a href='index.php?personal_page=orders'>here</a><br><br>Only the last 6 orders are shown here.");
define("pers_mess","To change your details please click <a href='index.php?personal_page=details'>here</a>");
define("pers_orders","Current / Previous Order");
define("pers_ord","Ordered/Unpaid");
define("pers_page","Personal Page");
define("pers_payed","Payed");
define("pers_reemit","Remade");
define("pers_res","Reserved");
define("pers_send","Sent & Payed");
define("pers_unknown","Unknown Status - Contact Admin");
define("per_post","By post");
define("phone","Phone Number");
define("place","Seat");
define("places","Seat Nr.");
define("places_empty","Select a seat, please");
define("places_freed","Seats set to &apos;Free&apos; state");
define("places_not_freed","Seats not set to &apos;Free&apos; state");
define("places_occupied","Sorry! The selected seats were taken by another customer.");
define("places_remains"," Remain seats");
define("places_toomuch","This number of seats cannot be reservated");
define("place_map","Seat chart");
define("place_maps","Seat charts");
define("place_not_commanded","Seat is not ordered");
define("place_nr","Seat nr");
define("place_only_reserved","Seat only reserved, not ordered");
define("place_row","Row");
define("place_row_nr","Row number");
define("place_seat","Seat");
define("place_seat_nr","Seat number");
define("place_status_not_updated","Error: seat status not updated");
define("place_without_nr","Seat without number");
define("pleaselogin","Please login or register.<br /> To signup please follow the
        link: <a href='index.php?register_user=on'>Register</a>");
define("Please_login","<center><b>Please login or register to reserve seats.</b></center>");
define("pmp_height","Part height");
define("pmp_id","Part ID");
define("pmp_name","Part Name");
define("pmp_scene","Scene location");
define("pmp_scene_est","East");
define("pmp_scene_north","North");
define("pmp_scene_south","South");
define("pmp_scene_west","West");
define("pmp_shift","Shift rows");
define("pmp_width","Part width");
define("pmz_id","Record#");		//added lou5
define("pmz_ident","Zone#");	//added lou5
define("pmz_pm_id","Seat Chart ID #");	//added lou5
define("pmz_color","Color");
define("pmz_name","Name");
define("pmz_short_name","Nickname");
define("pm_add_title","Add a new chart");
define("pm_dir","Direction");
define("pm_dir_LR","Left to right");
define("pm_dir_RL","Right to left");
define("pm_first_row","Number of the first row");
define("pm_height","Chart height");
define("pm_id","Seat chart ID");
define("pm_image","Picture of the seat chart");
define("pm_img_url","URL of the image");
define("pm_name","Seat Chart Name");
define("pm_ort_id","Venue ID:");
define("pm_part","Seat chart part");
define("pm_parts","Seat chart parts");
define("pm_paypal_business","PayPal Account");	//added lou5
define("pm_paypal_url","PayPal url");	//added lou5
define("pm_shift","Shift rows");
define("pm_split","Split seat chart");
define("pm_title","All charts");
define("pm_update_title","Edit chart");
define("pm_used","Seat chart in use!");
define("pm_width","Chart width");
define("pm_zones","Zones");
define("pm_zone","Zone");
define("pop","Pop");
define("possible_actions","Possible actions");
define("post","Post");
define("phone_short","The phone number is too short");
define("phone_long","The phone number is too long");
define("preferences","Preferences");
define("previouspage","<<<<<<<");
define("prev","Previous");
define("price","Price");
define("prices","Price");
define("prices_in","Prices in");
define("printing_manual","Print order");
define("printing_wait","Tickets are printing, wait please");
define("print_order","Print order");
define("processed","Processed");
define("processed_unsent","Paid and Processed Orders Ready to be Sent");
define("program","Program");
define("pub_begin_failed","Transaction begin failed");
define("pub_begin_trans","Transaction begin");
define("pub_category_failed","Error: Category not published");
define("pub_confirm_msg","Publish this event?");
define("pub_failure","Error");
define("pub_places_failed","Error - Seats not published");
define("pub_places_published","Seats published");
define("pub_pm_locked","Seat chart blocked");
define("pub_status_updated","Status updated");
define("pub_success","Success");
define("purge","purge");
define("pwd_err","User not found or other problem occured");
define("pwd_forgot","Forgotten your password?");
define("pwd_is_sent","Your new password was sent to your e-mail");
define("pwd_note","Introduce here your e-mail address. Click on &apos;Send password&apos;
        and a new password will be sent to you by e-mail");
define("pwd_send","Send password");
//R
define("rang_nr","Row nr");
define("redefine","Redefine");
define("redefine_pm_zone","Zone redefine");
define("reemited","Reemitted");
define("reemitted","Reemitted");
define("reemit_order","Reemit the order with a new order no. and cancel this order?");
define("reemit_order_menu","Emit a new order with a new order number and order status &apos;
        Ordered&apos;. Put this order to status &apos;Reemited&apos;");
define("reemit_ticket","Reemit the ticket (recalculate unique barcode)? Ticket Nr:");
define("register","Register Here");
define("regist_weiter","Register");
define("remove","Remove");
define("remove_event_image","Remove event picture");
define("remove_event_mp3","Remove MP3");
define("remove_image","Remove picture");
define("remove_logo","Remove logo");
define("remove_pm_image","Delete image");
define("reservate","Reservate");
define("reservate_failed1","Internal error: impossible to save seats 1");
define("reservate_failed","Internal error: impossible to save seats ");
define("reserved","Reserved");
define("reserve","Reserve");
define("reserv_cancel","WARNING Reservation is CANCELED on Ordering!");
define("res","Reset");
define("restart_success","Restart success");
define("Resume_min","min.");
define("res_paypal","Reserve&amp;Paypal");
define("required","== pleas use !manadatory!");
define("rock","Rock");
define("row","Row");
//S
define("sacred","Church music");
define("salepoint_admin","Points of sale");
define("sale_point","Point of sale");
define("save","Save");
define("save_failed","Internal error: impossible to save the order ");
define("scene_h","images/scene_h_en.png");
define("scene_v","images/scene_v_en.png");
define("search","Search");
define("search_order","Search");
define("search_result","Search result");
define("search_title_codebar","Search barcode");
define("search_title_order","Search order");
define("search_title_place","Search seat");
define("search_title_user","Search patron");
define("seat","Seat");
define("seat_nr","Seat number");
define("seat_numbering","Seat numbering");
define("seat_row_nr","Row number");
define("select","Select");
define("select_category","Select a category");
define("select_seat","1.Select your seat(s) please");
define("sended","Sent");
define("send","Sent");
define("send_orders_printer","Send Orders to printer");
define("send_order_email","Send order by e-mail and change status to &apos;Sent&apos;");
define("send_order_post","Change status to &apos;Sent&apos;?");
define("send_password","Send password");
define("sent","Sent");
define("shared_ort_title","Shared venues");
define("shipment","Shipment");
define("shipment_price","Charges");
define("shopcart","Shopping Cart");
define("shopconfig_lastrun","Last Time Run");
define("shopconfig_lastrun_int","Order check interval");
define("shopconfig_posttocollect","Switch to Alt paymment");
define("shopconfig_restime","Reservation time. (<10 = off)");
define("shopconfig_restime_remind","When reminder email is sent");
define("shop","Order tickets");
define("shopping_cart","Your shopping cart");
define("shopping_cart_pos","Shopping cart");
define("shop_condition","Conditions: Information collected by the Organizers will
        be stored to handle post and payment. "); //changed lou5 (replaced Valborg Foundation)
define("shop_info","Select the desired number of tickets. Click on &apos;Next&apos;, to
        check and confirm your order. The tickets will be send to you by post.");
define("shortdate_format","%e %b %Y");
define("show_text_stats","Text"); //added lou5
define("show_grafik_stats","Graph"); //added lou5
define("signup","Sign up");
define("sign_in_first","Sign in first");
define("sorry","I am sorry");
define("split_pm","Split seat chart");
define("split_zones","Split by zones");
define("spoint_add_title","Add new point of sale");
define("spoint_cancel","Cancel order");
define("spoint_confirm_print","Confirm and Print");
define("spoint_order","Order");
define("spoint_title","All Points of sale");
define("spoint_update_title","Edit sale point");
define("sp","Point of sale");
define("start","Event begins");
define("start_date","Start date");
define("state","State");
define("stats","Statistics");
define("status","Status");
define("status_not_valid_for_repub","Status not valid for re-publish");
define("step_row","Row step");
define("step_seat","Seat step");
define("stop_success","Stop success");
define("styles","Styles");
define("sure_to_cancel","Cancel?");
define("sure_to_delete","Delete?");
//T
define("template_add_title","Add title");
define("template_admin","Templates");
define("template_id","ID");
define("template_name","Name");
define("template_status","Status");
define("template_title","All Templates");
define("template_ts","Timestamp");
define("template_type","Type");
define("template_type_email","email");
define("template_type_pdf","PDF");
define("template_type_pdf2","HTML2PDF");
define("template_update_title","Edit template");
define("theater","Theater");
define("NoImages","The email contains no images or files.");
define("tickets","Tickets");
define("tickets_nr","Quantity");
define("tickets_printing","Tickets will be printed, wait please");
define("tickets_update_done","Tickets updated");
define("tickets_update_failed","Tickets update failed");
define("ticket_already_checked","Ticket already checked");
define("ticket_deleted","Ticket deleted");
define("ticket_not_found","Ticket not found in database");
define("tick_exp_in","Tickets expire in");
define("time","Time");
define("time_format","%H:%M");
define("time_stamp","Time");
define("tnx_here","here");
define("tnx_mbr","Thank you!");
define("tnx_order_mess","Thank you very much! Your order was registered. To pay for your
        order follow the proccess below.<br><br>To view your order click");
define("too_low","Please entre a number larger than 0");
define("total","Total");
define("total_price","Total price");
define("total_without_charges","Total without charges");
define("to","To");
define("tot_tick_price","Total Ticket Price:");
define("to_pay","Check out");
define("trx_id","Transation ID");
define("type","Card type");
//U
define("undefined","undefined");
define("unprocessed_paid","Unprocessed Paid Orders");
define("unpub_begin_failed","Transaction not started");
define("unpub_begin_trans","Transaction started");
define("upload","Upload");
define("up_events","Upcoming Events");
define("userid","User id");
define("user","User");
define("user_address1","Address");
define("user_address","Address");
define("user_city","Town");
define("user_country","Country");
define("user_country_name","Country");
define("user_dont_exist","Your e-mail is not in our database.");
define("user_email","E-Mail");
define("user_fax","Fax");
define("user_firstname","First Name");
define("user_id","ID");
define("user_lastname","Last Name");
define("user_nickname","Nickname");
define("user_notice","To order your tickets please the following fields and click on &apos;
        Continue&apos;. Fields with (*) are mandatory. This information will stay confidential.
        We will not give out your information or sell it to others. Yo can also choose to
        become member and not to fill this form another time you order tickets.</i>Members
        entrance is at the bottom of this page.</i>");
define("user_organizer_ids","Organizer");
define("user_phone","Phone");
define("user_prefs","Preferences");
define("user_prefs_pdf","Open Orders in Acrobat");
define("user_prefs_pdt","Send Orders to printer");
define("user_state","State");
define("user_state_name","State");
define("user_status","Status");
define("user_zip","Zip");	//changed lou5
define("usrupd_info","To update your settings please enter your current password.");
//V
define("valable_until","Card expires");
define("valid_tickets","Valid tickets:");
define("various_dates","Various dates");
define("venue","Location");
define("view","View");
define("view_cart","Cart");
define("view_handling","Order handling");
define("view_order","View order");
define("view_order_details","View details");
//W
define("warenkorb","Your cart");
define("warenkorb_title","Your cart");
define("weiter","Continue");
define("welcome","Welcome");
define("without_fee","Without fee");
//X
define("xl_end","End date");
define("xl_start","Start date");
define("xl_view_title","Sales data");
define("x_tick","x Tickets");
//Y
define("yes","YES");
define("your_addr","Your address");
define("yp","Yellowpay");
//Z
define("zip","Zip");	//changed lou5
define("zone","Zone");

//new defines
define('unpublish_event_group','unpublish_event_group' );
define('unpublish','Unpublish');
define('publish_event_group', 'publish_event_group');
define('publish', 'Publish' );
define('Archive','Archive' );
//define('reserved','Reserved');//chris updated
define('category_status', 'category_status' );
define('category_new_size_title', 'Change catagory size');
define('category_new_size','New size');

define('act_oke',     '<h3>Your account is now active. You may now log in.</h3>');
define('act_error',   'Your account could not be activated. Please re-check the link or contact the system administrator.');
define('act_uselink', 'Please use the link that has been sent to your email address.');

define('pos_calender_info','To Book/Reserve Tickets, select an event from the list below.');
define('pos_cart_info','Check the tickets below: to add more click "Order More Tickets"<br>'.
       'Check the Delivery method and Payment Method.<br>'.
       'To reserve the tickets click "Reserve Tickets Button".<br>');
define('select_seat_info', ', the seat name will appear if you hover your mouse over it.<br>'.
       'Free Seats are Green, Red Seats are Taken.');

define('pos_timestampt','Time stamp');
define('pos_deleteorder','Delete Order?');
define('pos_reorder_info','To Order Tickets Click below:<br><font color="red">WARNING old order is CANCELED on Re-Order! </font>');
define('pos_selectuser','Either Create a new user, or select an exsiting user if they have already purchased from us before.');
define('pos_freetickets','Free / Complimentary Tickets');
define('pos_exsistingusers','Exsisting Users');
define('pos_userlist','List of Box office users:');
define('pos_gobacktoorders','Click to go back to list of Processed Orders');
define('pos_ticketready','The tickets have there ID and Order ID on them and are ready to to be posted?');
define('pos_clicktosent','Click To Set to Sent!');
define('pos_nextorder','Next Processed Order');
define('pos_gotounprocessed','Click to go back to list of UnProcessed Orders');
define('pos_processorder','Processed Order? The Order ID and Ticket IDs been noted?');
define('pos_clicktoproc','Click To Finish Processing!');
define('pos_nextunprocessed','Next Unprocessed Paid Order');
define('pos_clicktoview','Click to View and Process');
define('pos_listpaidunprocessed','<p>List of <u>paid</u> <b>but</b> <u>Unprocessed</u> orders</p>');
define('pos_listpaidunsent','<p>List of <b>paid, processed</b> but <u>Unsent</u> orders</p>');
define('pos_listpaidsent','<p>List of <u>completed/sent</u> orders</p>');
define('pos_paidlist','Paid List');
define('pos_unsentlist','UnSent List');
define('pos_sentlist','Sent List');
define('pos_sentorders','Sent Orders');
define('pos_checkdetails' ,'Check the details, If cash or check Click "Confirm and Print"<br>If you have to pay with Credit/Debit Card click the "PayNow" button and Follow the Paypal instructions.');
define('pos_checkdetails2','Check the details, And Procced to "Confirm" or "Cancel" the order.');
define('pos_checkdate','First Check you have the right date, Then choose catergory of seats, this just determins the cost and area. Then click continue.');
define('pos_homepage','Home Page');
define('pos_currenttickets','Current Tickets');
define('pos_booktickets','Book Tickets');
define('pos_holdtickets','Hold Tickets');
define('shopconfig_delunpaid','Global Delete Unpaid Orders');
define('shopconfig_user_activate','Users checkout level');
define('index_admin','Home');
define('current_version','version:');
define('InfoWebVersion',   "Server Software");
define('InfoPhpVersion',   "PHP Version");
define('InfoMysqlVersion', "MySQL Version");
define('InfoUserCount',    "User count:");
define('InfoGroupCount',   "Group count:");
define('InfoVenueCount',   "Venue count:");
define('InfoEventCount',   "Event count:");
define('InfoAdminCount',   "Admin count:");
define("system_summary","System Summary");
define("unused_guests","Unused guests");

//Users Need to activate?

?><?php
// defines added at: 2009-05-22T13:20:39+02:00
define('Reservated', 'Reservated');
?><?php
// defines added at: 2009-05-22T13:34:27+02:00
define('imp_export_admin', "Import /Export");
define('guest_info', "Fill your details here, so that the ticket can be send to you. <br> Already a regular customer? Fill at the right side, your email address and password.");
define('mand_all', "All inputfields are required.");
define('password1', "Choice password");
define('eventlist_info', 'Please select an upcomming event from below.');
define('shop_info2', "For this event are no tickets for sale.");
define('cart_total', "Shopping Cart Total:");
define('user_address2', "Address");
define('user_nospam', "Security Code");
define('nospam_info', "Please type the code to the right into the box.");
define('payment_fee', "Fee");
define('per_mail', "per email");
define('pwd_min', "(min 6 letters)");
define('pwd_second_missing', "Second Password missing.");
define('pwd_to_short', "Password too short.");
define('pwd_not_thesame', "The passwords you entered do not match.");
define('invalid_zip', "Postcode you entered is invalid");
?><?php
// defines added at: 2009-05-22T14:19:24+02:00
define('www', 'webshop');
define('dts_month_arr', 'January|February|March|April|May|June|July|August|September|October|November|December');
define('dts_day_arr', 'Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday');
define("login_button","OK");
?><?PHP
define("becomememberorguest","Register as member or quest");
define("becomeguest","Register as guest");
define("users_admin","System managers");
define('act_restrict_all'       , 'Only activated members');
define('act_restrict_later'     , 'New members are allowed');
define('act_restrict_w_guest'   , 'New members and guests');
define('act_restrict_quest_only', 'Only guest users');
define('admin_user_title','All system administrators');
define('organizer_user_title','All event organizers');
define('act_enter_code','You can complete your activation by filling the box below with the activation code that is send to you by email. Or click on the link in the email.');
define('act_enter_title','Place your activation code here:');
define('act_code','Activation code:');
define('nav_first','first');
define('nav_prev',' < ');
define('nav_next',' > ');
define('nav_last','last');
define('shopconfig_check_pos',"Don't check POS orders");
define('shopconfig_maxres','Max tickets allowed');
define('res_delay','Ticket timeout');
define('cart_delay','mycart timeout');
define('Handling_Delete_Unpaid','Delete Unpaid Payments');

define('handling_no_alt','No Alt');
define('handling_alt','Alt Handling Method');

define('act_sent','The activation email has been sent. Please check your in box for a link.');
define('act_err', 'The activation email could not be sent, please check you have the correct email address.');
define('resend_activation','Resend Activation Email');
define('success_activate','You have successfully activated your account.<br /> You may now login.');
define('index_user_count','<b>POS:</b> %d, <b>Guests:</b> %d, <b>Members:</b> %d/%d/%d');
define('index_ort_count','%d');
define('index_events_count','<b>Pub:</b> %d, <b>New:</b> %d, <b>Nosale:</b> %d, <b>Trash:</b> %d, <b>Total:</b> %d');
define('index_admins_count','<b>Admins:</b> %d, <b>Organizers:</b> %d, <b>Controlers:</b> %d, <b>Total:</b> %d');
define('admin_user_update_title','All Administrators');
define('option_others_title','Other options');
define('order_event_list_title','Order overview per event');

define('AutoCancel_order','Auto Cancel: Failed to order.');
define('AutoCancel_paying','Auto Cancel: Failed to pay for order.');

define('old_event','<center><B>This event is expired and can&apos;t be ordered anymore.</b></center>');
define('clear_selection','Clear Selection');
define('show_seats','Seating Chart');

define('check_condition', "Please accept the terms");

?>