#time_format="%I:%M %p"

define("time_format","%H:%M");
define("date_format",'%e %b %Y');
define("longdate_format",'%Y-%m-%d %H:%M:%S');
define("shortdate_format",'%e %b %Y');
define("home","Home");
define("act_name",'Klant activeren');
define("act_mess_line1","Please check you email to activate your account.");
define("act_mess_line2","99.9% of the time you will recive your email straight away, if do not recive something please check your spam folder or deleted folder. The email contains no images or files.");
define("act_mess_line3","Any problems or if you havent recived an activation email within a few hours. Please follow the following <strong>link</strong>");
                 In normale gevallen zal de email direct worden ontvangen, mocht u niets ontvangen controleer dan eerst uw spam- of verwijderde-items folder. The email bevat geen afbeeldingen of bestanden.
                 Zijn er problemen of heeft u het activeringsbericht niet onvangen binnen een aantal uren, dan kunt u <strong>hier</strong> de email opnieuw versturen."""

define("agb_name","Plaats u verkoopkondities in het bestand 'agb.html'");
define("calendar","Calender");
define("cart_cont_mess1","Please check your order, to change your tickets remove the ones you have reserved and click 'Order More Tickets'.");
define("cart_cont_mess2","You have 15 minutes before your reserved tickets are released back to sale, so please either order more tickets or continue with your order. Thank you.");
                You have 15 minutes before your reserved tickets are released back to sale, so please either order more tickets or continue with your order. Thank you."""

define("shopping_cart","Uw winkelwagen");
define("cart_empty","Uw winkelwagen is leeg.");
define("event","Event");
define("tickets","Tickets");
define("total","Totaal");
define("expires_in","Expires in");
define("total_price","Totaal prijs");
define("shopcart","Shopping Cart");
define("valid_tickets","Valid tickets");
define("expired_tickets","Expired tickets");
define("tick_exp_in","Bestelling verloopt in");
define("x_tick","x kaarten");
define("view_order","Toon bestellingen");
define("checkout","Afrekenen");
define("no_tick_res","Er zijn geen kaarten gereserveerd");
define("Resume_min","min.");
define("tot_tick_price","Totaalprijs bestelde kaarten:");
define("row","Rij");
define("normal","Normaal");
define("remove","Verwijder");
define("expired","VERLOPEN");
define("order_more_tickets","Bestel meer tickets");
define("cat_description","Seating Sections and prices");
define("cat_ticketsection","Ticket Section");
define("cat_ticketprice","Toegangsprijs");
define("category_sold","Uitverkocht");
define("prices_in","Prijzen in");
define("select_category","Selecteer een categorie");
define("order_limit","Order limit");
define("sign_in_first","sign_in_first");
define("select_seat","1.Selecteer uw plaatsen aub.");
define("click_on_reserve","2.Klik op 'Reserveer'");
define("number_seats","Aantal plaatsen");
define("only_rows_numbered","Alleen rijen zijn genummerd");
define("reserve","Reserveer");
define("Please_login","Om kaarten te reserveren dient u eerst in te Logen of u te registeren");
define("cc_name","Eigennaar van Credit card");
define("cc_number","Credit card nummer");
define("cc_exp","Verloop datum");
define("cc_code","Controle nr");
define("pay","Betaal");

#paypal_return



define("pay_accept","Betaling geaccepteerd");
define("pay_refused","Betaling niet geaccepteerd");
define("order_id","Order ID");
define("trx_id","Transactie ID");
define("discount","Korting");
define("doors_open","deuren open");
define("dates_localities","Data en locaties");
define("various_dates","verschillende data");
define("date","Datum");
define("venue","Locatie");
define("time","Tijd");
define("indexpage","Index");
define("event_groups","Event Groep");

#event_type.tpl



define("et_classics","Classical music");
define("et_jbf","Jazz/Blues/Funk");
define("et_pr","Pop/Rock");
define("et_folk","Folk");
define("et_theater","Theater");
define("et_humour","Humor");
define("et_church","Church music");
define("et_opbal","Opera/Ballet");
define("et_music","Music");
define("et_other","Anders");
define("et_cinema","Cinema");
define("et_expo","Expo");
define("et_party","Party");

#event_types.tpl



define("styles","Stijlen");

#forgot_password.tpl



define("pwd_sent","Uw nieuwe wachtwoord is verzonden naar uw emailadres");
define("pwd_err","Lid niet gevonden of een ander probleem is opgetreden");
define("pwd_forgot","Uw wachtwoord vergeten?");
define("pwd_note","Vul hier uw emailadres in, klik op 'Verstuur wachtwoord' en het nieuwe wachtwoord wordt naar uw emailadres verzonden.");
define("pwd_send","Verstuur wachtwoord");
define("helpme","Help informatie");
define("becomemamber","Registeer u als gebruiker");
define("memberinfo","Vul hieronder uw adresgegevens in. Om kaarten te kopen dient u zich aan te melden. Dit kunt u het beste doen voordat u de kaarten gaat reserveren.");
define("password","Wachtwoord");
define("confirmpassword","bevestig uw wachtwoord");
define("agrement","Ik heb de verkoopvoorwaarde gelezen en ga hiermee accoord.");
define("mayuse","I ga accoord dat '{$organizer->organizer_name}' mijn gegevens gebruikt om mij informatie te versturen over toekomstige activiteiten en aanverwante zaken.");
define("signup","Aanmelden");

#just_registre



define("bcm_mbr","Wordt lid");
define("tnx_mbr","Dank u wel!");
define("note_mbr","Controleer uw email");
define("log_error","Probleem bij het aanmelden");
define("log_err_wrong_usr","Verkeerde gebruikersnaam of wachtwoord opgegeven! Probeer het opnieuw, vergeet niet dat zowel de gebruiksnaam al wachtwoord hoofdlettergevoelig zijn.<br> Als u uw wachtwoord bent klik dan <a href='forgot_password.php'><strong>hier</strong></a>.");
define("log_err_not_act","<p>Sorry, dit account is nog niet geactiveerd.<br />Activeer uw account eerst, alstubieft!</p><p>Controleer uw email voor uw activatie kode. Controleer zonodig ook uw spam folder. In dit mailtje staat een link die u kunt gebruiken om dit account te activeren.</p><p>Heeft u, na een aantal uur, nogsteeds niets ontvangen, klik dan <a href='resend_activation.php'<b>hier</b></a> om de activatie code opnieuw te verzenden.</p>");

#last_event_li



define("next_events","Volgende events");
define("up_events","Concertagenda");

#order_confirm



define("order_reg","Order geregisteerd");
define("tnx_order","Dank u wel! Uw bestelling is geregisteerd.");
define("tnx_mess","Om uw bestelling te betalen volgt u onderstaande procedure.<br><br>Om uw bestelling te bekijken klik");
define("tnx_here","hier");

#order_preview



define("handlings","Betalingen");
define("payment","Betaling");
define("shipment","Verzending");
define("order_it","Order");
define("limit","Helaas, u heeft het maximum aantal te reserveren kaarten bereikt. Klik <a href='index.php?personal_page=orders'>hier</a> om uw bestellingen te bekijken.");
define("orclick","Of klik hiernaast om:");

#paypal_cancel



define("pay_cancel","Betaling geannuleerd");
define("pers_orders","Huidige/voorgaande bestellingen");
define("go_back","Klik hier om terug te gaan");
define("ordered","Besteld");
define("order_date","Order datum");
define("status","Status");
define("cancelled","Geannuleerd");
define("reemitted","Afgewezen");
define("sent","Verstuurd");
define("notsent",""Niet verzonden");
define("paid","betaald");
define("notpaid","Niet betaald");
define("seat","Stoelen");
define("zone","Zone");
define("price","Prijs");
define("autocancel","Na de opgegeven tijd wordt de bestelling automatisch geannuleerd");
define("buytimeleft","U heeft nog ~DAYS~ Dagen, ~HOURS~ uren, ~MINS~ Min. en, ~SECS~ Seconde over om de kaart(en) te kopen!");
define("payhere","<br><br>Om nu te betalen, klik hier:");
define("paytimeleft","U heeft nog ~MINS~ Min. en, ~SECS~ Seconde over om de kaart(en) te kopen!");
define("number_tickets","Aantal tickets");
define("userid","Gebruikersnummer");
define("ordertickets",'Klik hieronder om uw kaarten te bestellen:');
define("reserv_cancel",'Opties');
define("options",'Personlijke gegevens');
define("personal",'Persoonlijke gegegevens');
define("categry",'Categorie');
define("orders",'Bestellingen');
define("id",'ID');
define("reserved",'Gereserveerd');
define("user","Klant");
define("pers_mess","Klik <a href='index.php?personal_page=details'>hier</a> om uw gegevens aan te passen");
define("pers_mess2","Alleen de 6 laatste bestellingen worden getoond.<br><br>Klik <a href="index.php?personal_page=orders">hier</a> om uw bestellingen te bekijken of te aan te passen.");
define("ordernumber","Bestelnummer");
define("Orderdate","Besteldatum");
define("pers_cancel","Geannuleerd");
define("pers_reemit","Remade");
define("pers_res","Gereserveerd");
define("pers_send","Betaald & verzonden");
define("pers_payed","Betaald");
define("pers_ord","Besteld/Niet betaald");
define("pers_unknown","Onbekende status");

#programm.tpl



define("program","Programma");
define("div_dates","Verschillende data");
define("unprocessed_paid","Onverwerkte betaalde bestellingen");
define("processed","Uitgevoerd");
define("processed_unsent","Betaald en verwerkte bwestelling is Klaar om te worden verzonden");
define("act_sent","Uw activatie email is verzonden naar uw emailadres");
define("act_err","Gebruiker niet gevonden of is al geactiveerd (controleer foutcode)");
define("act_notarr","Activatie email nogsteeds niet ontvangen?");
define("act_note","Vul hieronder uw emailadres in en klik vervolgens op 'Verzenden' zodat een nieuwe activatie email naar dit adres verzonden wordt.");
define("act_send","Verzend");
define("order_status_changed","De status ven de bestelling is aangepast");

#user.tpl     #user.tpl



define("pers_info","Persoonlijke informatie");
define("user_notice",""""Vul de onderstaande velden in om uw kaarten bestellen en klik op 'Vervolgen'. Invoervelden met (*) zijn verplicht.");
              De ingevoerde gegevens zijn blijven vertrouwelijk. Wij geven uw uw gegevens we of verkopen deze aan anderen.
              U kunt er ook voor kiezen om lid te worden zodat u, bij een volgenmde bestelling, niet nogmaals de gegevens hoeft in te voeren.
              <i>Leden toegang vind u onderaan deze pagina.</i>"""



define("check_cond","Ik heb de verkoopvoorwaarde gelezen en ga hiermee akkoord.");
define("continue","Vervolgen");
define("member","Vul hieronder uw emailadres en wachtwoord in, zoals u die heeft opgegeven tijdens het registreren op deze site.<br><br>");
define("pleaselogin","Melden u aan of registreer u zelf. Klik <a href='index.php?register_user=on'>hier</a> om u te kunnen registreren.");

#user_address.#user_address.tpl



define("your_addr","Uw adres");

#user_form.tpl#user_form.tpl



define("lastname","Achternaam");
define("firstname","Voornaam");
define("address","Adres");
define("zip","Postcode");
define("city","Woonplaats");
define("state","Provincie");
define("country","Land");
define("phone","telefoon");
define("fax","Fax");
define("welcome","Welkom");
define("logout","Afmelden");
define("pers_page","Personlijke Pagina");
define("email","Email");
define("register","Hier registeren");
define("forgot_pwd","Wachtwoord&nbsp;vergeten?");
define("total_without_charges","Totaal zonder kosten");
define("charges","kosten");


#pos



define("preferences","Voorkeuren");
define("shopping_cart_pos","Winkelwagen");
define("cart_empty_pos","Geen orders om af te sluiten");
define("homepage","Homepage");
define("event_start","Event begind");
define("event_sold","Event uitverkocht");
define("order_details","Bestelling gegevens");
define("print_order","Order afdrukken");
define("cancel_and_delete","Status aangepast naar &#146;geannuleerd&#146; en tickets verwijderd");
define("date_venue","Datum, Plaats");
define("confirm_and_print","Bevestig en afdrukken");
define("cancel_order","Order annuleren");
define("tickets_printing","Tickets worden afgedrukt, even wachten");
define("without_fee","zonder kosten (fee)");
define("save","Bewaar");
define("send_orders_printer","Verstuur orders naar de printer");
define("open_with_acrobat","Open Orders in Acrobat");
define("cancel_ticket","annuleer ticket");
define("from","Van");
define("to","Naar");
define("actions","Acties");
define("prev","Vorige");
define("next","Volgende");
define("order_canceled","Order geannulleerd");
define("pay_reg","Betaling geregisteerd");
define("invalid_name","Onjuiste naam");
define("invalid_date","Onjuiste datum");
define("invalid_number","Onjuist credit card nummer");
define("cannot_store","Interne fout: Kan decredit card informatie niet opslaan");
define("cannot_seal","Interne fout: Cannot seal credit card info");
define("discounts","Kortingen");
define("place_nr","Plaats Nr.");
define("categories_and_prices","Categorien and prijzen");
?>
